version: '3.8'

services:

  nginx:
    build:
      context: ./
      dockerfile: config/docker/nginx.Dockerfile
    container_name: ${CONTAINER_SERVER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${NGINX_PORT_HTTP}:80
      - ${NGINX_PORT_HTTPS}:443
      - ${VUE_PORT}:3000
    volumes:
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PATH_PROJECT}:/var/www/php
      - ${PATH_VUE_PROJECT}:/var/www/vue
      - ./logs/nginx:/var/log/nginx
      - ./ssl:/etc/nginx/listen
#      - ./certbot:/var/www/certbot
#      - ./certbot/conf:/etc/nginx/listen
      - ./scripts/nginx:/var/scripts
    networks:
      - project

  php:
    build:
      context: ./
      dockerfile: config/docker/php.Dockerfile
    container_name: ${CONTAINER_PHP}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${PHP_PORT}:9000
      - ${SUPERVISOR_PORT}:9001
    volumes:
      - ${PATH_PROJECT}:/var/www
      - ./config/supervisor:/etc/supervisor
      - ./config/supervisor/conf.d:/etc/supervisor/conf.d
      - ./logs/supervisor:/var/log/supervisor
      - ./scripts/php:/var/scripts
    networks:
      - project

  postgres:
    build:
      context: ./
      dockerfile: config/docker/postgres.Dockerfile
    container_name: ${CONTAINER_POSTGRES}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - project

  rabbitmq:
    build:
      context: ./
      dockerfile: config/docker/rabbitmq.Dockerfile
    container_name: ${CONTAINER_RMQ}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
      RABBITMQ_NODENAME: ${RMQ_NODE_NAME}
      #RABBITMQ_ERLANG_COOKIE: ${RMQ_COOKIE}
      RABBITMQ_LOGS: /var/log/rabbitmq/log/rabbitmq.log
    ports:
      - ${RMQ_PORT_CONNECT}:5672
      - ${RMQ_PORT_URI}:15672
    volumes:
      - ./logs/rabbitmq:/var/log/rabbitmq
      - ./data/rabbitmq:/var/lib/rabbitmq
    #- ./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    networks:
      - project

  mail:
    build:
      context: ./
      dockerfile: config/docker/mail.Dockerfile
    container_name: ${CONTAINER_MAIL}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - ${MAIL_PORT_SMTP}:1025
      - ${MAIL_PORT_HTTP}:8025
    networks:
      - project

  golang:
    build:
      context: ./
      dockerfile: config/docker/go.Dockerfile
    container_name: ${CONTAINER_GOLANG}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    tty: true
    ports:
      - ${GOLANG_PORT}:5462
    volumes:
      - ${PATH_GOLANG_PROJECT}:/var/www
      - ./logs/golang:/var/log
      - ./scripts/go:/var/scripts
    networks:
      - project

  redis:
    build:
      context: ./
      dockerfile: config/docker/redis.Dockerfile
    container_name: ${CONTAINER_REDIS}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./config/redis:/usr/local/etc/redis
      - ./logs/redis:/var/log
      - ./data/redis:/data
    networks:
      - project

  vue:
    build:
      context: ./
      dockerfile: config/docker/vue.Dockerfile
    container_name: ${CONTAINER_VUE}
    tty: true
    environment:
      TZ: ${TZ}
    ports:
      - ${VUE_PORT_DEV}:8080
    restart: unless-stopped
    volumes:
      - ${PATH_VUE_PROJECT}:/var/www
      - ./scripts/vue:/var/scripts
      - ./logs/vue:/root/.npm/_logs
    networks:
      - project

  mongodb:
    build:
      context: ./
      dockerfile: config/docker/mongodb.Dockerfile
    container_name: ${CONTAINER_MONGODB}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
    volumes:
      - ./data/mongodb:/data/db
      - ./scripts/mongodb:/var/scripts
      - ./logs/mongodb:/var/log/mongodb
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - project

#  certbot:
#    build:
#      context: ./
#      dockerfile: config/docker/certbot.Dockerfile
#    container_name: ${CONTAINER_CERTBOT}
#    restart: unless-stopped
#    volumes:
#      - ./certbot/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw
#      - ./logs/certbot:/var/log/letsencrypt
#    networks:
#      - project

networks:
  project:
    driver: bridge