version: '4'

services:

  nginx:
    build:
      context: ./
      dockerfile: config/docker/nginx.Dockerfile
    container_name: ${CONTAINER_SERVER}
    restart: always
    environment:
      TZ: ${TZ}
    ports:
      - ${NGINX_PORT_HTTP}:80
      - ${NGINX_PORT_HTTPS}:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PATH_PROJECT}:/var/www
      - ./logs/nginx:/var/log/nginx
    networks:
      - project

  php:
    build:
      context: ./
      dockerfile: config/docker/php.Dockerfile
    container_name: ${CONTAINER_PHP}
    restart: always
    environment:
      TZ: ${TZ}
    ports:
      - ${PHP_PORT}:9000
      - ${SUPERVISOR_PORT}:9001
    volumes:
      - ./config/php/:/usr/local/etc/php/conf.d/custom-php.ini
      - ${PATH_PROJECT}:/var/www
      - ./config/supervisor:/etc/supervisor
      - ./config/supervisor/conf.d:/etc/supervisor/conf.d
      - ./logs/supervisor:/var/log/supervisor
      - ./scripts:/var/scripts
    networks:
      - project

  db:
    build:
      context: ./
      dockerfile: config/docker/db.Dockerfile
    container_name: ${CONTAINER_DB}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - project

  adminer:
    image: adminer
    container_name: ${CONTAINER_ADMINER}
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - project

  rabbitmq:
    build:
      context: ./
      dockerfile: config/docker/rabbitmq.Dockerfile
    container_name: ${CONTAINER_RMQ}
    restart: always
    environment:
      TZ: ${TZ}
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
      RABBITMQ_NODENAME: ${RMQ_NODE_NAME}
      #RABBITMQ_ERLANG_COOKIE: ${RMQ_COOKIE}
      RABBITMQ_LOGS: /var/log/rabbitmq/log/rabbitmq.log
    ports:
      - ${RMQ_PORT_CONNECT}:5672
      - ${RMQ_PORT_URI}:15672
    volumes:
      - ./logs/rabbitmq:/var/log/rabbitmq
      - ./data/rabbitmq:/var/lib/rabbitmq
    #- ./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    networks:
      - project

  mail:
    build:
      context: ./
      dockerfile: config/docker/mail.Dockerfile
    container_name: ${CONTAINER_MAIL}
    restart: always
    ports:
      - ${MAIL_PORT_SMTP}:1025
      - ${MAIL_PORT_HTTP}:8025
    networks:
      - project

  golang:
    build:
      context: ./
      dockerfile: config/docker/go.Dockerfile
    container_name: ${CONTAINER_GOLANG}
    restart: always
    ports:
      - ${GOLANG_PORT}:5462
    volumes:
      - ${PATH_GOLANG_PROJECT}:/var/golang
      - ./logs/golang:/var/log
    networks:
      - project

  redis:
    build:
      context: ./
      dockerfile: config/docker/redis.Dockerfile
    container_name: ${CONTAINER_REDIS}
    restart: always
    ports:
      - ${RADIS_PORT}:6379
    volumes:
      - ./config/redis:/usr/local/etc/redis
      - ./logs/redis:/var/log
      - ./data/redis:/data
    networks:
      - project

networks:
  project:
    driver: bridge