services:

  reverse-proxy:
    build:
      context: ./
      dockerfile: config/docker/traefic.Dockerfile
      args:
        VERSION: ${TRAEFIC_VERSION}
    container_name: ${TRAEFIC_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - ${TRAEFIC_PORT_HTTP:-80}:80
      - ${TRAEFIC_PORT_HTTPS:-443}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik
      - ./ssl:/etc/certificate
      - ./logs/traefik:/etc/log/traefik
    networks:
      - project

  nginx:
    build:
      context: ./
      dockerfile: config/docker/nginx.Dockerfile
      args:
        VERSION: ${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PHP_WEB_PATH_PROJECT}:/var/www/php
      - ${NODE_PATH_PROJECT}:/var/www/js
      - ./logs/nginx:/var/log/nginx
      - ./ssl:/etc/nginx/listen
      #      - ./certbot:/var/www/certbot
      #      - ./certbot/conf:/etc/nginx/listen
      - ./scripts/nginx:/var/scripts
    networks:
      - project

  php-fpm:
    build:
      context: ./
      dockerfile: config/docker/php-fpm.Dockerfile
      args:
        VERSION: ${PHP_VERSION}
    container_name: ${PHP_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ${PHP_WEB_PATH_PROJECT}:/var/www/php
      - ./config/supervisor:/var/config/supervisor
      - ./config/supervisor/conf.d:/etc/supervisor/conf.d
      - ./logs/supervisor:/var/log/supervisor
      - ./scripts/php:/var/scripts
      - ./config/php:/var/config/php
      - ${PROTO_PATH}:/var/proto
    networks:
      - project

  postgres:
    build:
      context: ./
      dockerfile: config/docker/postgres.Dockerfile
      args:
        VERSION: ${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - project

  rabbitmq:
    build:
      context: ./
      dockerfile: config/docker/rabbitmq.Dockerfile
      args:
        VERSION: ${RMQ_VERSION}
    container_name: ${RMQ_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
      RABBITMQ_NODENAME: ${RMQ_NODE_NAME}
      #RABBITMQ_ERLANG_COOKIE: ${RMQ_COOKIE}
      RABBITMQ_LOGS: /var/log/rabbitmq/log/rabbitmq.log
    ports:
      - ${RMQ_PORT_CONNECT}:5672
    volumes:
      - ./logs/rabbitmq:/var/log/rabbitmq
      - ./data/rabbitmq:/var/lib/rabbitmq
    #- ./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    networks:
      - project

  buggregator:
    build:
      context: ./
      dockerfile: config/docker/buggregator.Dockerfile
      args:
        VERSION: ${BUGGREGATOR_VERSION}
    container_name: ${BUGGREGATOR_CONTAINER}
    restart: unless-stopped
    environment:
      PERSISTENCE_DRIVER: db
      DB_DRIVER: pgsql
      DB_DATABASE: ${BUGGREGATOR_DB_NAME}
      DB_HOST: ${BUGGREGATOR_DB_HOST}
      DB_PORT: ${BUGGREGATOR_DB_PORT}
      DB_USERNAME: ${BUGGREGATOR_DB_USER}
      DB_PASSWORD: ${BUGGREGATOR_DB_PASS}
    ports:
      - ${BUGGREGATOR_PORT_SMTP}:1025
      - ${BUGGREGATOR_PORT_DUMPER}:9912
      - ${BUGGREGATOR_PORT_LOGGING}:9913
    networks:
      - project

  golang:
    build:
      context: ./
      dockerfile: config/docker/go.Dockerfile
      args:
        VERSION: ${GOLANG_VERSION}
    container_name: ${GOLANG_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    tty: true
    ports:
      - ${GOLANG_PORT_GRPC}:5463
      - ${GOLANG_PORT_METRICS}:5464
    volumes:
      - ${GOLANG_PATH_PROJECT}:/var/www
      - ./logs/golang:/var/log
      - ./scripts/go:/var/scripts
      - ${PROTO_PATH}:/var/proto
    networks:
      - project

  redis:
    build:
      context: ./
      dockerfile: config/docker/redis.Dockerfile
      args:
        VERSION: ${REDIS_VERSION}
    container_name: ${REDIS_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./config/redis:/usr/local/etc/redis
      - ./logs/redis:/var/log
      - ./data/redis:/data
    networks:
      - project

  node:
    build:
      context: ./
      dockerfile: config/docker/node.Dockerfile
      args:
        VERSION: ${NODE_VERSION}
    container_name: ${NODE_CONTAINER}
    tty: true
    environment:
      TZ: ${TZ}
    ports:
      - ${NODE_PORT_PREVIEW}:4173
    restart: unless-stopped
    volumes:
      - ${NODE_PATH_PROJECT}:/var/www
      - ./scripts/node:/var/scripts
      - ./logs/node:/root/.npm/_logs
    networks:
      - project

  mongodb:
    build:
      context: ./
      dockerfile: config/docker/mongodb.Dockerfile
      args:
        VERSION: ${MONGODB_VERSION}
    container_name: ${MONGODB_CONTAINER}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
    volumes:
      - ./data/mongodb:/data/db
      - ./scripts/mongodb:/var/scripts
      - ./logs/mongodb:/var/log/mongodb
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - project

  prometheus:
    build:
      context: ./
      dockerfile: config/docker/prometheus.Dockerfile
      args:
        VERSION: ${PROMETHEUS_VERSION}
    container_name: ${PROMETHEUS_CONTAINER}
    restart: unless-stopped
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
    networks:
      - project

  grafana:
    build:
      context: ./
      dockerfile: config/docker/grafana.Dockerfile
      args:
        VERSION: ${GRAFANA_VERSION}
    container_name: ${GRAFANA_CONTAINER}
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - project

  logstash:
    build:
      context: ./
      dockerfile: config/docker/logstash.Dockerfile
      args:
        VERSION: ${LOGSTASH_VERSION}
    container_name: ${LOGSTASH_CONTAINER}
    restart: unless-stopped
    environment:
      discovery.seed_hosts: logstash
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "5001:5000/tcp"
      - "5001:5000/udp"
      - "6000:6000"
      - "9600:9600"
      - "5044:5044"
    volumes:
      - ./config/logstash/config/:/var/config/logstash
      - ./scripts/logstash:/var/scripts
      - ./logs/logstash/:/usr/share/logstash/logs/
      - ./config/logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - project

  kibana:
    build:
      context: ./
      dockerfile: config/docker/kibana.Dockerfile
      args:
        VERSION: ${KIBANA_VERSION}
    container_name: ${KIBANA_CONTAINER}
    restart: unless-stopped
    volumes:
      - ./data/kibana:/usr/share/kibana/data
    networks:
     - project


  elasticsearch:
    build:
      context: ./
      dockerfile: config/docker/elastic.Dockerfile
      args:
        VERSION: ${ELASTIC_VERSION}
    container_name: ${ELASTIC_CONTAINER}
    environment:
      discovery.type: single-node
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: unless-stopped
    ports:
      - ${ELASTIC_PORT}:9200
    volumes:
      - ./data/elastic/:/usr/share/elasticsearch/data
      - ./logs/elastic/:/usr/share/elasticsearch/logs
    networks:
      - project

  #  certbot:
  #    build:
  #      context: ./
  #      dockerfile: config/docker/certbot.Dockerfile
  #      args:
  #        VERSION: ${VERSION_CERTBOT}
  #    container_name: ${CONTAINER_CERTBOT}
  #    restart: unless-stopped
  #    volumes:
  #      - ./certbot/:/var/www/certbot/:rw
  #      - ./certbot/conf/:/etc/letsencrypt/:rw
  #      - ./logs/certbot:/var/log/letsencrypt
  #    networks:
  #      - project

  php-cli:
    build:
      context: ./
      dockerfile: config/docker/php-cli.Dockerfile
      args:
        VERSION: ${CHAT_PHP_VERSION}
        RR_VERSION: ${RR_VERSION}
    container_name: ${CHAT_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "8010:8010"
      - "6001:6001"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ${CHAT_PATH}:/var/www
      - ./scripts/php:/var/scripts
      - ./config/php:/var/config/php
      - ./config/chat:/var/config/rr
    networks:
      - project

  centrifugo:
    build:
      context: ./
      dockerfile: config/docker/centrifugo.Dockerfile
      args:
        VERSION: ${CENTRIFUGO_VERSION}
    volumes:
      - ./config/centrifugo:/centrifugo
      - ./scripts/centrifugo:/var/scripts
    container_name: ${CENTRIFUGO_CONTAINER}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - ${CENTRIFUGO_PORT}:8000
    networks:
      - project

  swagger:
    build:
      context: ./
      dockerfile: 'config/docker/swagger.Dockerfile'
      args:
        VERSION: ${SWAGGER_VERSION}
    container_name: ${SWAGGER_CONTAINER}
    restart: unless-stopped
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - ./swagger:/swagger
    networks:
      - project


  temporal:
    build:
      context: ./
      dockerfile: 'config/docker/temporal.Dockerfile'
      args:
        VERSION: ${TEMPORAL_VERSION}
    container_name: ${TEMPORAL_CONTAINER}
    environment:
      DB: postgres12
      DB_PORT: ${TEMPORAL_DB_PORT}
      POSTGRES_USER: ${TEMPORAL_DB_USER}
      POSTGRES_PWD: ${TEMPORAL_DB_PASS}
      POSTGRES_SEEDS: ${TEMPORAL_DB_SEEDS}
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yml
    volumes:
      - ./config/temporal:/etc/temporal/config/dynamicconfig
    restart: unless-stopped
    networks:
      - project

  temporal-ui:
    build:
      context: ./
      dockerfile: 'config/docker/temporal-ui.Dockerfile'
      args:
        VERSION: ${TEMPORAL_UI_VERSION}
    container_name: ${TEMPORAL_UI_CONTAINER}
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_UI_ADDRESS}
      TEMPORAL_CORS_ORIGINS: ${TEMPORAL_UI_CORS_ORIGIN}
    restart: unless-stopped
    networks:
      - project


  minio:
    build:
      context: ./
      dockerfile: 'config/docker/minio.Dockerfile'
      args:
        VERSION: ${MINIO_VERSION}
    container_name: ${MINIO_CONTAINER}
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - ${MINIO_PORT}:9001
    volumes:
      - ./data/minio:/data
    restart: unless-stopped
    networks:
      - project

networks:
  project:
    ipam:
      driver: default
      config:
        - subnet: 172.0.13.0/24