---
global:
  scrape_interval: 10s


scrape_configs:

  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: [prometheus:9090]


  - job_name: sso
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: [golang:5464]