version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

http:
  address: '0.0.0.0:8010'
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    debug: true
    num_workers: 1
    supervisor:
      max_worker_memory: 100

server:
  command: 'php app.php'
  relay: pipes

centrifugo:
  proxy_address: tcp://0.0.0.0:10001
  grpc_api_address: tcp://0.0.0.0:10000
  pool:
    num_workers: 3