version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

#http:
#  address: '0.0.0.0:8010'
#  middleware:
#    - gzip
#    - static
#  static:
#    dir: public
#    forbid:
#      - .php
#      - .htaccess
#  pool:
#    debug: true
#    num_workers: 1
#    supervisor:
#      max_worker_memory: 100

server:
  command: 'php /var/www/register/artisan temporal:registration-workflow'
  relay: pipes

#centrifugo:
#  proxy_address: tcp://0.0.0.0:10001
#  grpc_api_address: tcp://0.0.0.0:10000
#  pool:
#    num_workers: 3

temporal:
  address: 'temporal:7233'