http:
  routers:
    kibana:
      entryPoints:
        - http
        - https
      service: kibana-host
      rule: Host(`kibana.localhost`)

  services:
    kibana-host:
      loadBalancer:
        servers:
          - url: http://kibana:5601
        passHostHeader: true