http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    router-http:
      rule: HostRegexp(`^.+\.localhost$`)
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      service: noop

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://localhost"