http:
  routers:
    minio:
      entryPoints:
        - http
        - https
      service: minio-host
      rule: Host(`minio.localhost`)

  services:
    minio-host:
      loadBalancer:
        servers:
          - url: http://minio:9000
        passHostHeader: true