http:
  routers:
    nginx-backend:
      entryPoints:
        - http
        - https
      service: nginx-backend-host
      rule: Host(`backend.php.localhost`)

    nginx-js:
      entryPoints:
        - http
        - https
      service: nginx-js-host
      rule: Host(`web.js.localhost`)

    nginx-register:
      entryPoints:
        - http
        - https
      service: nginx-register-host
      rule: Host(`register.php.localhost`)

  services:
    nginx-backend-host:
      loadBalancer:
        servers:
          - url: http://nginx:80
        passHostHeader: true

    nginx-js-host:
      loadBalancer:
        servers:
          - url: http://nginx:3000
        passHostHeader: true

    nginx-register-host:
      loadBalancer:
        servers:
          - url: http://nginx:81
        passHostHeader: true