http:
  routers:
    react:
      entryPoints:
        - http
        - https
      service: react-host
      rule: Host(`dev.web.js.localhost`)

  services:
    react-host:
      loadBalancer:
        servers:
          - url: http://node:3000
        passHostHeader: true