http:
  routers:
    rabbit:
      entryPoints:
        - http
        - https
      service: rabbit-host
      rule: Host(`rabbit.localhost`)

  services:
    rabbit-host:
      loadBalancer:
        servers:
          - url: http://rabbitmq:15672
        passHostHeader: true