http:
  routers:
    reverse-proxy:
      entryPoints:
        - http
        - https
      service: reverse-proxy-host
      rule: Host(`traefik.localhost`)

  services:
    reverse-proxy-host:
      loadBalancer:
        servers:
          - url: http://reverse-proxy:8080
        passHostHeader: true