http:
  routers:
    temporal:
      entryPoints:
        - http
        - https
      service: temporal-host
      rule: Host(`temporal.localhost`)

  services:
    temporal-host:
      loadBalancer:
        servers:
          - url: http://temporal-ui:8080
        passHostHeader: true